spring.application.name=secureapp
server.port=8443
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=password
server.ssl.key-store-type=PKCS12

spring.datasource.url=jdbc:h2:mem:secure_db
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=